---
mysql_package: mysql-server
mysql_service: mysql
mysql_bind_address: "127.0.0.1"
mysql_port: 3306
mysql_root_password: "change_me_securely"
mysql_databases: []
#  - name: example_db
#    encoding: utf8mb4
#    collation: utf8mb4_0900_ai_ci
mysql_users: []
#  - name: example_user
#    password: user_password
#    priv: 'example_db.*:ALL'
#    host: '%'
