---
- name: Install MariaDB Server and Python dependencies
  ansible.builtin.package:
    name:
      - "{{ mariadb_package }}"
      - python3-pymysql
    state: present

- name: Apply MariaDB configuration template (Debian/Ubuntu)
  ansible.builtin.template:
    src: server.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    mode: '0644'
  notify: Restart MariaDB
  when: ansible_os_family == "Debian"

- name: Apply MariaDB configuration template (RHEL)
  ansible.builtin.template:
    src: server.cnf.j2
    dest: /etc/my.cnf.d/server.cnf
    mode: '0644'
  notify: Restart MariaDB
  when: ansible_os_family == "RedHat"

- name: Ensure MariaDB service is running
  ansible.builtin.service:
    name: "{{ mariadb_service }}"
    state: started
    enabled: yes

- name: Set root password
  community.mysql.mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host_all: yes
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Remove anonymous users
  community.mysql.mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Remove test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Create databases
  community.mysql.mysql_db:
    name: "{{ item.name }}"
    encoding: "{{ item.encoding | default('utf8mb4') }}"
    collation: "{{ item.collation | default('utf8mb4_general_ci') }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  loop: "{{ mariadb_databases }}"

- name: Create database users
  community.mysql.mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    host: "{{ item.host | default('%') }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  loop: "{{ mariadb_users }}"
