---
- name: Install MariaDB Server
  ansible.builtin.package:
    name: "{{ mariadb_package }}"
    state: present

- name: Ensure MariaDB service is running and enabled
  ansible.builtin.service:
    name: "{{ mariadb_service }}"
    state: started
    enabled: yes

- name: Configure bind address
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: "bind-address = {{ mariadb_bind_address }}"
    backup: yes
  notify: Restart MariaDB
  when: ansible_os_family == "Debian"

# RedHat/CentOS might use different config path
- name: Configure bind address (RedHat)
  ansible.builtin.lineinfile:
    path: /etc/my.cnf.d/server.cnf
    regexp: '^bind-address'
    line: "bind-address = {{ mariadb_bind_address }}"
    backup: yes
  notify: Restart MariaDB
  when: ansible_os_family == "RedHat"
