---
- name: Install MySQL Server and Python dependencies
  ansible.builtin.package:
    name:
      - "{{ mysql_package }}"
      - python3-pymysql
    state: present

- name: Apply MySQL configuration template (Debian/Ubuntu)
  ansible.builtin.template:
    src: server.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    mode: '0644'
  notify: Restart MySQL
  when: ansible_os_family == "Debian"

- name: Apply MySQL configuration template (RHEL)
  ansible.builtin.template:
    src: server.cnf.j2
    dest: /etc/my.cnf.d/mysql-server.cnf
    mode: '0644'
  notify: Restart MySQL
  when: ansible_os_family == "RedHat"

- name: Ensure MySQL service is running
  ansible.builtin.service:
    name: "{{ mysql_service }}"
    state: started
    enabled: yes

- name: Set root password
  community.mysql.mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host_all: yes
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Remove anonymous users
  community.mysql.mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Remove test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create databases
  community.mysql.mysql_db:
    name: "{{ item.name }}"
    encoding: "{{ item.encoding | default('utf8mb4') }}"
    collation: "{{ item.collation | default('utf8mb4_0900_ai_ci') }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  loop: "{{ mysql_databases }}"

- name: Create database users
  community.mysql.mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    host: "{{ item.host | default('%') }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  loop: "{{ mysql_users }}"
