---
postgresql_version: "17"
postgresql_package: "postgresql-{{ postgresql_version }}"
postgresql_service: postgresql
postgresql_port: 5432
postgresql_listen_addresses: "localhost"

# Configuration paths (Default to Debian style, overrided in tasks for RHEL distros)
postgresql_conf_dir: "/etc/postgresql/{{ postgresql_version }}/main"
postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"

postgresql_users: []
#  - name: app_user
#    password: app_password
#    db: app_db
#    priv: "ALL"

postgresql_databases: []
#  - name: app_db
#    owner: app_user

postgresql_hba_entries: []
#  - type: host
#    database: all
#    user: all
#    address: 0.0.0.0/0
#    method: md5
