- name: User Setup
  hosts: db-servers
  become: true
  roles:
    - role: users
      users_create:
        - name: admin
          groups: ["wheel"]
          ssh_keys:
            - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDCy2+ngWQ2ub48qKMGrkd4oafkABbezCb+GYzZ2GvOD/CBIc0SbmeaunSOLsNNiJjCQ131kLF9Q2guo8enRxtdRqkGmYV4rhojuwqyNLIzoWxkaVAgahGqiEMlTRuKtRwX9Bme8Fk+Kfs+oTgZmo7XtWSNjswU8bUQK6g84k0fVmQ/+i6E+bk9jVd9oyc1kxmmLWwLEVXDhuNsRDp3JOtPsy97LPRTqcfF/Zy25I3mwWPVmeoj+pMekQaCYa1TqU9ZwCsf9o+hh3/hUtgojSMLgk0YRSCslq/H0T0tOKnIijzbIJYyJFy0wYdvAC07MWekWfLxGgyRhWrFdMNzdcdqGZVvS6DqqTK1H3BhMHhiyQn/l6gF8uMVETcf4Y4EaN4mW2ZhhuwQdvSS8hw9eMXOx8YRpzQN1wZvLid52jSIZxGY0XAIH9DFG27n/r3f9xdMAY6E6KQavy8Qp7jzIe8fiJffiizjb/I02u32Y+pUpDv9tdOyDyOiVcBxdR6lMVs2z6znriVWH1SRW+rUIaWusNT/K0pK3KOFu70zy1vhIH/t+WIIP62bSQyRAUoj6Ei5++2nKcIHTWtxRwUuNXln892q+QZgbliYqXYATOK31bc5JENtk4tRrfL/9QCOgm6paFwqGPWPoHFshpl7ZA23IT38KEbFQD9eh/ABcZLKrw== gedeon@Valentines-MacBook-Pro.local"

        - name: kloudke
          groups: ["wheel"]
          ssh_keys:
            - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDCy2+ngWQ2ub48qKMGrkd4oafkABbezCb+GYzZ2GvOD/CBIc0SbmeaunSOLsNNiJjCQ131kLF9Q2guo8enRxtdRqkGmYV4rhojuwqyNLIzoWxkaVAgahGqiEMlTRuKtRwX9Bme8Fk+Kfs+oTgZmo7XtWSNjswU8bUQK6g84k0fVmQ/+i6E+bk9jVd9oyc1kxmmLWwLEVXDhuNsRDp3JOtPsy97LPRTqcfF/Zy25I3mwWPVmeoj+pMekQaCYa1TqU9ZwCsf9o+hh3/hUtgojSMLgk0YRSCslq/H0T0tOKnIijzbIJYyJFy0wYdvAC07MWekWfLxGgyRhWrFdMNzdcdqGZVvS6DqqTK1H3BhMHhiyQn/l6gF8uMVETcf4Y4EaN4mW2ZhhuwQdvSS8hw9eMXOx8YRpzQN1wZvLid52jSIZxGY0XAIH9DFG27n/r3f9xdMAY6E6KQavy8Qp7jzIe8fiJffiizjb/I02u32Y+pUpDv9tdOyDyOiVcBxdR6lMVs2z6znriVWH1SRW+rUIaWusNT/K0pK3KOFu70zy1vhIH/t+WIIP62bSQyRAUoj6Ei5++2nKcIHTWtxRwUuNXln892q+QZgbliYqXYATOK31bc5JENtk4tRrfL/9QCOgm6paFwqGPWPoHFshpl7ZA23IT38KEbFQD9eh/ABcZLKrw== gedeon@Valentines-MacBook-Pro.local"
