- name: Create provisioning user and setup SSH access
  hosts: local
  become: true
  roles:
    - role: users
      users_create:
        - name: admin
          uid: 1050
          groups: ["wheel"]

        - name: kloudke
          groups: ["wheel"]
